/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BakeDialog: typeof import('./src/components/BakeDialog.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskStream: typeof import('./src/components/TaskStream.vue')['default']
    TerminalOutput: typeof import('./src/components/TerminalOutput.vue')['default']
  }
}
